### ISSUE TITLE
Use english in Wiki

### ISSUE THREAD

**Issue by astrand** [xHasKx/WialonIPSEmulator#2]
I think the Wiki page (https://github.com/xHasKx/WialonIPSEmulator/wiki) should be written in English, so that it is readable by a wider audience. Also note that it is impossible to translate the page using Google Translate, since GitHub forces HTTPS, which Google Translate does not support.

**Comment by xHasKx** [comment]
Help page ( https://github.com/xHasKx/WialonIPSEmulator/wiki/Help ) is written on two languages, but you are right, main Wiki page should be on English.
Soon I'll fix it.

**Comment by xHasKx** [comment]
Wiki translated to English
