### ISSUE TITLE
Simulate network delays

### ISSUE THREAD

**Issue by astrand** [xHasKx/WialonIPSEmulator#4]
Another feature which would be nice would be to simulate network delays. For example, when a message is sent with a single TCP "send", it usually arrives at the client side in a single TCP "recv" as well. Servers must be prepared for only recieving a partial message, such as "#D#181013;084100;5355.09272;N;02732.". It would be nice if the emulator could optionally split messages and send them using multiple "send" API calls, with some time in between.

**Comment by xHasKx** [comment]
> Servers must be prepared for only recieving a partial message, such as "#D#181013;084100;5355.09272;N;02732.".

This is a server-side feature, server always should be prepared for this.
Emulation of this behavior is not related to Wialon IPS protocol and will not be implemented.

**Comment by astrand** [comment]
I don't understand this reasoning. The project is described as "...send location/sensors, text and image messages to monitoring system like Wialon to test its ability to manipulate and handle location data...". Being able to send a partial message (to test the servers ability to handle such data) certainly fits this description.

**Comment by xHasKx** [comment]
When you developing receiving server - the first step is receive entire and valid message. Only after that server should handle it.
If message is partial or malformed - server should not handle it at all. This is easy part, a "transport protocol", and it always should work.

The goal of Wialon IPS Emulator is to send data in Wialon IPS data format, not to test how server can handle TCP packets.
Like browser sending HTTP requests.
But browser is not created for sending malformed or partial HTTP requests. Browser is not a tool for testing HTTP server.

**Comment by astrand** [comment]
> When you developing receiving server - the first step is receive entire and valid message. Only after that server should handle it.
> If message is partial or malformed - server should not handle it at all. This is easy part, a "transport protocol", and it always should work.

I don't agree that this is easy. In most languages, you will have to manually manage a receive buffer. This is a context where bugs are common. 

> The goal of Wialon IPS Emulator is to send data in Wialon IPS data format, not to test how server can handle TCP packets.

From this comment, it seems like you have misunderstood this issue. I'm certainly not talking about testing the TCP implementation. I'm talking about sending 100% valid IPS data, but sent using multiple send() system calls (or similar) so that the IPS message is fragmented over multiple network packets. 

> Like browser sending HTTP requests.
> But browser is not created for sending malformed or partial HTTP requests. Browser is not a tool for testing HTTP server.

Sorry, but this is not a good comparison. The WialonIPSEmulator is not a "normal" end user application, nor a standard IPS client. It's more of a test and development tool, so an option for testing fragmentation handling of servers is not very strange.

**Comment by xHasKx** [comment]
astrand, Wialon IPS messages designed to simplify receiving server logic - all messages ends with "\r\n" bytes.
So server just need to "glue" all packets until "\r\n" bytes received, regardless how much recv() was called.
Besides, big Wialon IPS messages still may be splited into few network packets when receiving on server (internet through GPRS), so it always should be prepared for "network delays".
This is a "transport layer" of Wialon IPS protocol, and it should always work this way on server side.

**Comment by xHasKx** [comment]
Also, we are on GitHub, you always can fork this project and implement what you need and then do pull request.
